### ISSUE TITLE
Unable to recreate CIFAR10 performance

### ISSUE THREAD

**Issue by iamgroot42** [ganeshdg95/Leveraging-Adversarial-Examples-to-Quantify-Membership-Information-Leakage#2]
Hi,

First off, thanks a lot for making the codebase for your paper available- very straight-forward and easy to use! I was using the norm-based attack (`Linf` norm) to run MIA using WideResNets (the same models used in [LiRA](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9833649)) but seem to get an AUC of a 0.538. Since it's much lower than even the LOSS attack, I was wondering if something might have changed in the AutoAttack that you used in your experiments and the one right now? This is how I compute the signal, which I think is exactly how you do it in the repository:

```python
adversary = AutoAttack(self.model, norm="Linf", eps=1, version="standard")
adv = adversary.run_standard_evaluation(x_.unsqueeze(0), y_.unsqueeze(0), bs=1)
signal = ch.norm(adv - x_, p=float(norm)).cpu().item()
```

**Comment by Tardouse** [comment]
I have the same problem as you.

**Comment by ganeshdg95** [comment]
Hello,

Thank you for your interest in our code. Your results seem plausible and I don't think there is necessarily an error. 

In the experiments that were published in the paper there was an error in the preprocessing that was making MIAs more effective in general. Someone pointed out this error to us months after the publication, but since there are no errata in conference proceedings we were not able to correct our results. However, the code in this repository was corrected and thus the results that differ from those of the publication.

My thesis should be publicly available soon, and there you can find the updated results and compare to yours.

**Comment by z872845991** [comment]
> Hello,
> 
> Thank you for your interest in our code. Your results seem plausible and I don't think there is necessarily an error.
> 
> In the experiments that were published in the paper there was an error in the preprocessing that was making MIAs more effective in general. Someone pointed out this error to us months after the publication, but since there are no errata in conference proceedings we were not able to correct our results. However, the code in this repository was corrected and thus the results that differ from those of the publication.
> 
> My thesis should be publicly available soon, and there you can find the updated results and compare to yours.

you can close this issue, because it is be solved. Thanks
